apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
          command:
            - "/cloud_sql_proxy"
            - "-instances=lidium:europe-west4:testvb=tcp:5432"
            - "-credential_file=/secrets/service_account.json"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              # The proxy's memory use scales linearly with the number of active
              # connections. Fewer open connections will use less memory. Adjust
              # this value based on your application's requirements.
              memory: 2Gi
              # The proxy's CPU use scales linearly with the amount of IO between
              # the database and the application. Adjust this value based on your
              # application's requirements.
              cpu: 1
            limits:
              cpu: 1
              memory: 2Gi
          volumeMounts:
            - name: demo-service-secret-volume
              mountPath: /secrets/
              readOnly: true
        - name: demo-service
          image: gcr.io/lidium/demo-service
          env:
            - name: DB_USER
              #TODO: extract from secrets
              value: "vborcea"
            - name: SPRING_DATASOURCE_PASSWORD
              #TODO: extract from secrets
              value: "vborcea"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://127.0.0.1:5432/testvb"
          resources:
            requests:
              cpu: 0.5
              memory: 300M
            limits:
              cpu: 0.5
              memory: 300M

      volumes:
        - name: demo-service-secret-volume
          secret:
            secretName: demo-service-secret

